# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TemperatureSampling.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemperatureSampling(object):
    def setupUi(self, TemperatureSampling):
        TemperatureSampling.setObjectName("TemperatureSampling")
        TemperatureSampling.resize(958, 671)
        self.centralwidget = QtWidgets.QWidget(TemperatureSampling)
        self.centralwidget.setObjectName("centralwidget")
        self.titleName = QtWidgets.QLabel(self.centralwidget)
        self.titleName.setGeometry(QtCore.QRect(290, 20, 451, 71))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.titleName.setFont(font)
        self.titleName.setObjectName("titleName")
        self.Probe = QtWidgets.QPushButton(self.centralwidget)
        self.Probe.setGeometry(QtCore.QRect(360, 150, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Probe.setFont(font)
        self.Probe.setObjectName("Probe")
        self.TemperatureMeasure = QtWidgets.QPushButton(self.centralwidget)
        self.TemperatureMeasure.setGeometry(QtCore.QRect(360, 350, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TemperatureMeasure.setFont(font)
        self.TemperatureMeasure.setObjectName("TemperatureMeasure")
        TemperatureSampling.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TemperatureSampling)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 21))
        self.menubar.setObjectName("menubar")
        TemperatureSampling.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TemperatureSampling)
        self.statusbar.setObjectName("statusbar")
        TemperatureSampling.setStatusBar(self.statusbar)

        self.retranslateUi(TemperatureSampling)
        QtCore.QMetaObject.connectSlotsByName(TemperatureSampling)

    def retranslateUi(self, TemperatureSampling):
        _translate = QtCore.QCoreApplication.translate
        TemperatureSampling.setWindowTitle(_translate("TemperatureSampling", "MainWindow"))
        self.titleName.setText(_translate("TemperatureSampling", "测温取样机器人视觉检测子系统"))
        self.Probe.setText(_translate("TemperatureSampling", "取样器视觉检测"))
        self.TemperatureMeasure.setText(_translate("TemperatureSampling", "测温枪视觉检测"))
