# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TemperatureMeasureInitial.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QRect, pyqtSignal


class Ui_TemperatureMeasureInitial(object):
    signal_show_LT = pyqtSignal(str)
    signal_show_RB = pyqtSignal(str)
    def setupUi(self, TemperatureMeasureInitial):
        TemperatureMeasureInitial.setObjectName("TemperatureMeasureInitial")
        TemperatureMeasureInitial.resize(944, 671)
        self.centralwidget = QtWidgets.QWidget(TemperatureMeasureInitial)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(540, 80, 401, 521))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.Status = QtWidgets.QLabel(self.groupBox)
        self.Status.setGeometry(QtCore.QRect(10, 10, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.Status.setFont(font)
        self.Status.setObjectName("Status")
        self.ROI = QtWidgets.QPushButton(self.groupBox)
        self.ROI.setGeometry(QtCore.QRect(110, 150, 211, 61))
        self.ROI.setObjectName("ROI")
        self.IP = QtWidgets.QLineEdit(self.groupBox)
        self.IP.setGeometry(QtCore.QRect(70, 60, 291, 71))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.IP.setFont(font)
        self.IP.setObjectName("IP")
        self.LT_show = QtWidgets.QTextBrowser(self.groupBox)
        self.LT_show.setGeometry(QtCore.QRect(30, 260, 121, 91))
        self.LT_show.setObjectName("LT_show")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 211, 111, 61))
        self.label.setObjectName("label")
        self.RB_Show = QtWidgets.QTextBrowser(self.groupBox)
        self.RB_Show.setGeometry(QtCore.QRect(240, 260, 121, 91))
        self.RB_Show.setObjectName("RB_Show")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(230, 210, 141, 51))
        self.label_2.setObjectName("label_2")
        self.template1 = QtWidgets.QPushButton(self.groupBox)
        self.template1.setGeometry(QtCore.QRect(110, 370, 161, 51))
        self.template1.setObjectName("template1")
        self.titleName = QtWidgets.QLabel(self.centralwidget)
        self.titleName.setGeometry(QtCore.QRect(310, 10, 390, 81))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.titleName.setFont(font)
        self.titleName.setObjectName("titleName")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(210, 60, 131, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Image.setFont(font)
        self.Image.setObjectName("Image")
        self.ImageShow = QtWidgets.QGraphicsView(self.centralwidget)
        self.ImageShow.setGeometry(QtCore.QRect(10, 130, 511, 471))
        self.ImageShow.setObjectName("ImageShow")
        TemperatureMeasureInitial.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TemperatureMeasureInitial)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 944, 21))
        self.menubar.setObjectName("menubar")
        TemperatureMeasureInitial.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TemperatureMeasureInitial)
        self.statusbar.setObjectName("statusbar")
        TemperatureMeasureInitial.setStatusBar(self.statusbar)

        self.retranslateUi(TemperatureMeasureInitial)
        QtCore.QMetaObject.connectSlotsByName(TemperatureMeasureInitial)

    def retranslateUi(self, TemperatureMeasureInitial):
        _translate = QtCore.QCoreApplication.translate
        TemperatureMeasureInitial.setWindowTitle(_translate("TemperatureMeasureInitial", "MainWindow"))
        self.groupBox.setTitle(_translate("TemperatureMeasureInitial", "初始化参数"))
        self.Status.setText(_translate("TemperatureMeasureInitial", "相机IP："))
        self.ROI.setText(_translate("TemperatureMeasureInitial", "框选安全区域"))
        self.IP.setText(_translate("TemperatureMeasureInitial", "192.168.0.122"))
        self.label.setText(_translate("TemperatureMeasureInitial", "Left_Top"))
        self.label_2.setText(_translate("TemperatureMeasureInitial", "Right_Bottom"))
        self.template1.setText(_translate("TemperatureMeasureInitial", "选取模板"))
        self.titleName.setText(_translate("TemperatureMeasureInitial", "测温枪视觉检测参数初始化"))
        self.Image.setText(_translate("TemperatureMeasureInitial", "相机图像"))
